name: client_super_chollo
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.0-204.0.dev <4.0.0'


dependencies:
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  envied: ^0.3.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  http: ^0.13.0
  stream_transform: ^2.1.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  http_interceptor: ^1.0.1
  shared_preferences: ^2.0.17
  json_annotation: ^4.8.0
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  bloc_test: ^9.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.6.1
  envied_generator: ^0.3.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  injectable_generator: ^2.1.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

